# CMake generated Testfile for 
# Source directory: C:/Slime/programs/thirdparty/cppast/test
# Build directory: C:/Slime/programs/thirdparty/cppast/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unit_test "C:/Slime/programs/thirdparty/cppast/test/Debug/cppast_test.exe" "~[integration]")
  set_tests_properties(unit_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;50;add_test;C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unit_test "C:/Slime/programs/thirdparty/cppast/test/Release/cppast_test.exe" "~[integration]")
  set_tests_properties(unit_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;50;add_test;C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unit_test "C:/Slime/programs/thirdparty/cppast/test/MinSizeRel/cppast_test.exe" "~[integration]")
  set_tests_properties(unit_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;50;add_test;C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unit_test "C:/Slime/programs/thirdparty/cppast/test/RelWithDebInfo/cppast_test.exe" "~[integration]")
  set_tests_properties(unit_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;50;add_test;C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;0;")
else()
  add_test(unit_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(integration_test "C:/Slime/programs/thirdparty/cppast/test/Debug/cppast_test.exe" "[integration]")
  set_tests_properties(integration_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;51;add_test;C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(integration_test "C:/Slime/programs/thirdparty/cppast/test/Release/cppast_test.exe" "[integration]")
  set_tests_properties(integration_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;51;add_test;C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(integration_test "C:/Slime/programs/thirdparty/cppast/test/MinSizeRel/cppast_test.exe" "[integration]")
  set_tests_properties(integration_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;51;add_test;C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(integration_test "C:/Slime/programs/thirdparty/cppast/test/RelWithDebInfo/cppast_test.exe" "[integration]")
  set_tests_properties(integration_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;51;add_test;C:/Slime/programs/thirdparty/cppast/test/CMakeLists.txt;0;")
else()
  add_test(integration_test NOT_AVAILABLE)
endif()
subdirs("../_deps/catch-build")
